version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    platform: linux/arm64
    environment:
      POSTGRES_DB: poc_db
      POSTGRES_USER: poc_user
      POSTGRES_PASSWORD: poc_password
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro
    networks:
      - poc-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poc_user -d poc_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  poc-net:
    driver: bridge
